CREATE OR REPLACE FUNCTION FN_GET_CUST_NAME(IN_CUST_ID NUMBER) RETURN VARCHAR2 AS

VAR_CUST_NAME VARCHAR2(100):= 'Not found';

BEGIN
    SELECT CUST_NAME INTO VAR_CUST_NAME FROM MASTER_CUSTOMER WHERE CUST_ID = IN_CUST_ID;
    DBMS_OUTPUT.PUT_LINE(VAR_CUST_NAME);
RETURN VAR_CUST_NAME;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Customer with id: '|| IN_CUST_ID||' not found');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error in getting customer name');    
END;